export const dayNames=[
    'Dimenche',
    'Lundi', 
    'Mardi', 
    'Mercredi', 
    'Jeudi', 
    'Vendredi', 
    'Samedi'
]

export const locals=[
    
    {
        language:'Francais',
        local:'fr-FR',
        dayNames:[
            'Dimenche',
            'Lundi', 
            'Mardi', 
            'Mercredi', 
            'Jeudi', 
            'Vendredi', 
            'Samedi'
        ]
    },
    {
        language:'Arabe',
        local:'ar-AR',
        dayNames:[
            'الأحد',
            'الإثنين', 
            'الثلاثاء', 
            'الأربعاء', 
            'الخميس', 
            'الجمعة', 
            'السبت'
        ]
    },
    {
        language:'English',
        local:'en-EN',
        dayNames:[
            'Sunday',
            'Monday', 
            'Tuesday', 
            'Wednesday', 
            'Thursday', 
            'Friday', 
            'Saturday'
        ]
    },
    {
        language:'spanish',
        local:'es-ES',
        dayNames:[
            'Domingo',
            'Lunes', 
            'Martes', 
            'Mercoles', 
            'Jueves', 
            'Viernes', 
            'Sabado'
        ]
    }
]